In [19]:
import pickle
import numpy as np

In [20]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [28]:
test_input = np.array([2,'male',31.0,0,0,10.5,'S'],dtype=object).reshape(1,7)
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [31]:
test_input[:,1].reshape(1,1).ndim

2

In [26]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))
test_input_sex

array([[0., 1.]])

In [33]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))
test_input_embarked

array([[0., 0., 1.]])

In [34]:
test_input_age = test_input[:,2].reshape(1,1)

In [37]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [38]:
test_input_transformed.shape

(1, 10)

In [39]:
clf.predict(test_input_transformed)

array([1], dtype=int64)

In [41]:
test_input[:,[0,1,2]]

array([[2, 'male', 31.0]], dtype=object)