In [1]:
import numpy as np
from sklearn.datasets import load_diabetes
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import random

In [2]:
X,y = load_diabetes(return_X_y=True)

In [3]:
X.shape

(442, 10)

In [4]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [5]:
LR = LinearRegression()

In [6]:
LR.fit(X_train,y_train)

LinearRegression()

In [7]:
r2_score(y_test,LR.predict(X_test))

0.4526027629719195

In [8]:
LR.intercept_

151.34560453985995

In [9]:
LR.coef_

array([  37.90402135, -241.96436231,  542.42875852,  347.70384391,
       -931.48884588,  518.06227698,  163.41998299,  275.31790158,
        736.1988589 ,   48.67065743])

In [10]:
class MBGDRegressor:
    def __init__(self,batch_size,learning_rate,epochs):
        self.lr = learning_rate
        self.epochs = epochs
        self.coef_ = None
        self.intercept_ = None
        self.batch_size = batch_size
    def fit(self,X_train,y_train):
        # intialize the coeff_
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])
        
        for i in range(self.epochs):
            for j in range(int(X_train.shape[0]/self.batch_size)):
                idx = random.sample(range(X_train.shape[0]),self.batch_size)
                y_hat = np.dot(X_train[idx],self.coef_)+self.intercept_
                intercept_der = -2*np.mean(y_train[idx]-y_hat)
                self.intercept_ = self.intercept_ - (self.lr*intercept_der)

                coef_der = -2*np.dot((y_train[idx]-y_hat),X_train[idx])
                self.coef_ = self.coef_ - (self.lr*coef_der)
                
    def predict(self,X_test):
        return np.dot(X_test,self.coef_)+self.intercept_
    def get_param(self):
        return self.coef_,self.intercept_
    

In [11]:
model = MBGDRegressor(batch_size=int(X_train.shape[0]/10),learning_rate=0.01,epochs=200)

In [12]:
model.fit(X_train,y_train)

In [13]:
model.get_param()

(array([  44.56876824, -227.88028719,  537.05264284,  328.79025095,
         -82.78418222, -128.51836451, -214.33700137,  151.9662402 ,
         398.39852397,   81.77181894]),
 150.40947738443953)

In [14]:
r2_score(y_test,model.predict(X_test))

0.456600654441358

In [16]:
from sklearn.linear_model import SGDRegressor

In [25]:
sgd = SGDRegressor(learning_rate='constant',eta0=0.1)

In [26]:
batch_size = 35
for i in range(100):
    idx = random.sample(range(X_train.shape[0]),batch_size)
    sgd.partial_fit(X_train[idx],y_train[idx])

In [27]:
sgd.coef_

array([  35.82961538, -107.43029011,  353.14398309,  248.14299578,
         -7.4727879 ,  -41.6249296 , -191.31304671,  152.50480957,
        280.42248691,  139.63513326])

In [28]:
sgd.intercept_

array([145.95177992])

In [29]:
r2_score(y_test,sgd.predict(X_test))

0.44053835204325664